# Generated by Django 3.0.5 on 2020-04-22 19:03

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_set', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MockSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(blank=True)),
                ('msnumber', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('quesnumber', models.IntegerField()),
                ('constraints', models.TextField()),
                ('example_input', models.TextField()),
                ('example_output', models.TextField()),
                ('solution', models.TextField()),
                ('generatorfile', models.FileField(upload_to=base.models.upload_GeneratorFile_location)),
                ('mockset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.MockSet')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcasenumber', models.IntegerField()),
                ('input', models.FileField(upload_to=base.models.upload_TestCaseInput_location)),
                ('output', models.FileField(upload_to=base.models.upload_TestCaseOutput_location)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Question')),
            ],
        ),
    ]
