# Generated by Django 3.0.5 on 2020-04-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockset',
            name='msnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mockset',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
    ]
