# Generated by Django 3.0.5 on 2020-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200423_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quesnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
